#docker-compose.yml
version: '3.7'

services:
  api:
    build: ./backend
    container_name: "model_api"
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000

  web:
    build: ./frontend
    container_name: "model_web"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 4242:4242